DROP DATABASE vehicles;
CREATE DATABASE IF NOT EXISTS vehicles;
USE vehicles;

CREATE TABLE users (
  id INT PRIMARY KEY AUTO_INCREMENT,
  NAME VARCHAR(255) NOT NULL,
  is_admin BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE vehicle_brands (
  id INT PRIMARY KEY AUTO_INCREMENT,
  NAME VARCHAR(255) NOT NULL
);

CREATE TABLE vehicle_types (
  id INT PRIMARY KEY AUTO_INCREMENT,
  NAME VARCHAR(255) NOT NULL,
  brand_id INT NOT NULL,
  FOREIGN KEY (brand_id) REFERENCES vehicle_brands(id)
);

CREATE TABLE vehicle_years (
  id INT PRIMARY KEY AUTO_INCREMENT,
  YEAR INT NOT NULL
);

CREATE TABLE vehicle_models (
  id INT PRIMARY KEY AUTO_INCREMENT,
  NAME VARCHAR(255) NOT NULL,
  type_id INT NOT NULL,
  FOREIGN KEY (type_id) REFERENCES vehicle_types(id)
);

CREATE TABLE pricelists (
  id INT PRIMARY KEY AUTO_INCREMENT,
  CODE VARCHAR(255) NOT NULL,
  price INT NOT NULL,
  year_id INT NOT NULL,
  model_id INT NOT NULL,
  FOREIGN KEY (year_id) REFERENCES vehicle_years(id),
  FOREIGN KEY (model_id) REFERENCES vehicle_models(id)
);

